---
# tasks file for ansible-endlessh

- name: Install required packages
  become: true
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ endlessh_packages }}'

- name: Clone endlessh git repository
  git:
    repo: 'https://github.com/skeeto/endlessh.git'
    dest: '/tmp/endlessh'

- name: Build endlessh
  become: true
  make:
    chdir: '/tmp/endlessh'
    target: install
    
